spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/FishPond
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234qwer
    dbcp2:
      max-idle: 100
      max-wait-millis: -1
      min-idle: 10
      initial-size: 5
    type: com.alibaba.druid.pool.DruidDataSource
  config:
    name: application.yml

#  data:
#    mongodb:
#      uri: mongodb://127.0.0.1:27017/test

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest



server:
  port: 8888
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /demo
    session:
      timeout: 100



mybatis:
  mapperLocations: classpath:mapping/*.xml
  typeAliasesPackage: com.entity

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

